version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    depends_on:
      - mariadb
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/SNS?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb/data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    environment:
      MYSQL_DATABASE: SNS
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"

  redis:
    image: redis:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "6379:6379"

    command: redis-server --appendonly yes  # 데이터 지속성을 위한 AOF 설정
    volumes:
            - redis-data:/data  # 데이터 영속성을 위한 볼륨 추가

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    restart: always

volumes:
  gradle-cache:
  portainer_data:
  redis-data:
