spring:
  datasource:
      url: jdbc:mariadb://localhost:3306/SNS
      username: root
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver


#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#

  ## 프로젝트 실행할때마다 배치가 자동실행 되는 것을 막음
  batch:
    job:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update  # or create, create-drop, validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10000  # JPA 배치 사이즈 (배치 처리용)
        order_inserts: true
        order_updates: true

  application:
    name: sns_project

server:
  port: 8080

logging:
  level:
    com.example.sns_project.batch.aspect: INFO

springdoc:
  packages-to-scan: com.example.sns_project.controller  # 컨트롤러 패키지 경로 수정
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

#    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


# security:
#   user:
#     name: user
#     password: password
